In [1]:
from train import *

In [2]:
import pandas as pd

df = pd.read_csv('./data/sample_submission.csv')
len(df['id'])

10357

In [4]:
model = ResNet('resnet18', pretrained=True)
data = DogData()
trainer = pl.Trainer(max_epochs=0, logger=False)
predictions = trainer.predict(model, datamodule=data)
len(predictions)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

2

In [6]:
len(predictions[0])

81

In [7]:
len(predictions[1])

81

In [8]:
def max_to_one(tensor):
    row_max_values, _ = torch.max(tensor, dim=1, keepdim=True)
    result_tensor = torch.where(tensor == row_max_values, torch.tensor(1.0), torch.tensor(0.0))

    return result_tensor

In [9]:
preds1 = [row.tolist() for item in predictions[0] for row in max_to_one(item)]

In [21]:
columns = df.columns.tolist()
columns.pop(0)
len(columns)

120

In [22]:
pd.DataFrame(preds1, columns=columns)

affenpinscher  afghan_hound  african_hunting_dog  airedale  \
0                0.0           0.0                  0.0       0.0   
1                0.0           0.0                  0.0       0.0   
2                0.0           0.0                  0.0       0.0   
3                0.0           0.0                  0.0       0.0   
4                0.0           0.0                  0.0       0.0   
...              ...           ...                  ...       ...   
10352            0.0           0.0                  0.0       0.0   
10353            0.0           0.0                  0.0       0.0   
10354            0.0           0.0                  0.0       0.0   
10355            0.0           0.0                  0.0       0.0   
10356            0.0           0.0                  0.0       0.0   

       american_staffordshire_terrier  appenzeller  australian_terrier  \
0                                 0.0          0.0                 0.0   
1                                 0.0          0.0                 0.0   
2                                 0.0          0.0                 0.0   
3                                 0.0          0.0                 0.0   
4                                 0.0          0.0                 0.0   
...                               ...          ...                 ...   
10352                             0.0          0.0                 0.0   
10353                             0.0          0.0                 0.0   
10354                             0.0          0.0                 0.0   
10355                             0.0          0.0                 0.0   
10356                             0.0          0.0                 0.0   

       basenji  basset  beagle  ...  toy_poodle  toy_terrier  vizsla  \
0          0.0     0.0     0.0  ...         0.0          0.0     0.0   
1          0.0     0.0     0.0  ...         0.0          0.0     0.0   
2          0.0     0.0     0.0  ...         0.0          0.0     0.0   
3          0.0     0.0     0.0  ...         0.0          0.0     0.0   
4          0.0     0.0     0.0  ...         0.0          0.0     0.0   
...        ...     ...     ...  ...         ...          ...     ...   
10352      0.0     0.0     0.0  ...         0.0          0.0     0.0   
10353      0.0     0.0     0.0  ...         0.0          0.0     0.0   
10354      0.0     0.0     0.0  ...         0.0          0.0     0.0   
10355      0.0     0.0     0.0  ...         0.0          0.0     0.0   
10356      0.0     0.0     0.0  ...         0.0          0.0     0.0   

       walker_hound  weimaraner  welsh_springer_spaniel  \
0               0.0         0.0                     0.0   
1               0.0         0.0                     0.0   
2               0.0         0.0                     0.0   
3               0.0         0.0                     0.0   
4               0.0         0.0                     0.0   
...             ...         ...                     ...   
10352           0.0         0.0                     0.0   
10353           0.0         0.0                     0.0   
10354           0.0         0.0                     0.0   
10355           0.0         0.0                     0.0   
10356           0.0         0.0                     0.0   

       west_highland_white_terrier  whippet  wire-haired_fox_terrier  \
0                              0.0      0.0                      0.0   
1                              0.0      0.0                      0.0   
2                              0.0      0.0                      0.0   
3                              0.0      0.0                      0.0   
4                              0.0      0.0                      0.0   
...                            ...      ...                      ...   
10352                          0.0      0.0                      0.0   
10353                          0.0      0.0                      0.0   
10354                          0.0      0.0                      0.

In [25]:
predictions[0][0].shape, predictions[1][0].shape

(torch.Size([128, 120]), torch.Size([640, 120]))

In [30]:
tmp = predictions[1][0][:5]

In [31]:
tmp.shape

torch.Size([5, 120])

In [34]:
tmp.shape

torch.Size([5, 120])

In [38]:
tmp.sum(dim=0)[31]

tensor(6.6875)

In [39]:
tmp.sum(dim=0)[109]

tensor(8.3306)

In [42]:
tmp = predictions[1][0]
tmp.shape

torch.Size([640, 120])

In [55]:
tmp.view(-1,5,tmp.shape[-1]).sum(dim=1)

tensor([[ 4.7246e+00, -9.4453e-01, -9.2844e-01,  ..., -7.3591e+00,
         -2.5798e+00,  4.8392e+00],
        [ 1.2414e+00, -1.8089e+00,  3.8826e+00,  ..., -5.3644e+00,
         -1.1778e+00,  2.6887e+00],
        [-2.8432e+00, -7.3294e+00, -2.5520e-01,  ..., -4.3879e+00,
          5.8176e+00,  8.1218e+00],
        ...,
        [-2.1636e+00, -3.8289e-02,  3.3641e-01,  ..., -2.8932e+00,
          1.5983e+00,  2.6288e+00],
        [-5.9772e-01, -2.3351e+00, -6.0127e+00,  ..., -1.2376e+00,
          1.0895e+00,  3.6525e+00],
        [-1.0216e+00, -2.0529e+00,  1.5538e-03,  ..., -4.4795e+00,
          5.1601e+00,  6.8866e+00]])

In [2]:
from train import *

model = ResNet('resnet18', pretrained=True)
data = DogData(five_crop=True)
trainer = pl.Trainer(max_epochs=0, logger=False, callbacks=Submission())
trainer.predict(model, datamodule=data);

/usr/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

In [1]:
from train import *

model = ResNet('resnet18', pretrained=True)
data = DogData(five_crop=False)
trainer = pl.Trainer(max_epochs=0, logger=False, callbacks=Submission())
trainer.predict(model, datamodule=data);

/usr/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

In [1]:
from train import *

model = ResNet('resnet152', pretrained=True)
model.load_state_dict(torch.load('./lightning_logs/ResNet152_mix_freeze_all/checkpoints/resnet152-epoch=09-step=5750.ckpt')['state_dict'])
data = DogData(five_crop=True, batch_size=32)
trainer = pl.Trainer(max_epochs=0, logger=False, callbacks=Submission())
trainer.predict(model, datamodule=data);

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

/root/kaggle/dog_breed_identification/callback.py:54: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  preds = [row.tolist() for item in predictions_centercrop for row in F.softmax(item)]
/root/kaggle/dog_breed_identification/callback.py:62: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  for row in F.softmax(item.view(-1, 5, item.shape[-1]).sum(dim=1))


In [1]:
from train import *

model = ResNet('resnet152', pretrained=True)
model.load_state_dict(torch.load('./lightning_logs/ResNet152_mix_freeze_all/checkpoints/resnet152-epoch=09-step=5750.ckpt')['state_dict'])
data = DogData(five_crop=False, batch_size=32)
trainer = pl.Trainer(max_epochs=0, logger=False)
predictions = trainer.predict(model, datamodule=data)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

In [4]:
predictions[0].argmax(dim=1)

tensor([ 61,  94,  40,  88, 109, 105,   6,  94,  59, 107, 109,  98,  78,  81,
          9,  69,  29,  98,  57,  93,  96, 101,  74,  67,  56,  54,  14,  51,
         40,   3,  46,  18])

In [9]:
predictions[0].softmax(dim=1)

tensor([[0.0006, 0.0008, 0.0014,  ..., 0.0015, 0.0023, 0.0009],
        [0.0006, 0.0005, 0.0014,  ..., 0.0026, 0.0012, 0.0012],
        [0.0012, 0.0074, 0.0014,  ..., 0.0049, 0.0027, 0.0013],
        ...,
        [0.0012, 0.0021, 0.0018,  ..., 0.0020, 0.0825, 0.0019],
        [0.0005, 0.0004, 0.0005,  ..., 0.0013, 0.0007, 0.0007],
        [0.0008, 0.0020, 0.0015,  ..., 0.0059, 0.0010, 0.0003]])

In [10]:
predictions[0].softmax(dim=1).argmax(dim=1)

tensor([ 61,  94,  40,  88, 109, 105,   6,  94,  59, 107, 109,  98,  78,  81,
          9,  69,  29,  98,  57,  93,  96, 101,  74,  67,  56,  54,  14,  51,
         40,   3,  46,  18])

In [12]:
torch.nn.functional.softmax(predictions[0])

/tmp/ipykernel_3728/1357955869.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.softmax(predictions[0])


tensor([[0.0006, 0.0008, 0.0014,  ..., 0.0015, 0.0023, 0.0009],
        [0.0006, 0.0005, 0.0014,  ..., 0.0026, 0.0012, 0.0012],
        [0.0012, 0.0074, 0.0014,  ..., 0.0049, 0.0027, 0.0013],
        ...,
        [0.0012, 0.0021, 0.0018,  ..., 0.0020, 0.0825, 0.0019],
        [0.0005, 0.0004, 0.0005,  ..., 0.0013, 0.0007, 0.0007],
        [0.0008, 0.0020, 0.0015,  ..., 0.0059, 0.0010, 0.0003]])

In [13]:
torch.nn.functional.softmax(predictions[0], dim=1)

tensor([[0.0006, 0.0008, 0.0014,  ..., 0.0015, 0.0023, 0.0009],
        [0.0006, 0.0005, 0.0014,  ..., 0.0026, 0.0012, 0.0012],
        [0.0012, 0.0074, 0.0014,  ..., 0.0049, 0.0027, 0.0013],
        ...,
        [0.0012, 0.0021, 0.0018,  ..., 0.0020, 0.0825, 0.0019],
        [0.0005, 0.0004, 0.0005,  ..., 0.0013, 0.0007, 0.0007],
        [0.0008, 0.0020, 0.0015,  ..., 0.0059, 0.0010, 0.0003]])

In [20]:
predictions[0].softmax(0).argmax(dim=1) == predictions[0].softmax(dim=1).argmax(dim=1)

tensor([ True,  True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True])

In [22]:
predictions[0].softmax(0).argmax(dim=1)

tensor([ 61,  94,  40,  88,  70, 105,   6,  94,  59, 107, 109,  98,  78,  81,
          9,  69,  29,  68,  57,  93,  96, 101,  74,  67,  56,  54,  14,  51,
         40,   3,  46,  18])

In [24]:
torch.nn.functional.softmax(predictions[0]).argmax(dim=1) == torch.nn.functional.softmax(predictions[0], dim=1).argmax(dim=1)

/tmp/ipykernel_3728/211225831.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.softmax(predictions[0]).argmax(dim=1) == torch.nn.functional.softmax(predictions[0], dim=1).argmax(dim=1)


tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True])

In [1]:
from train import *

model = ResNet('resnet152', pretrained=True)
model.load_state_dict(torch.load('./lightning_logs/ResNet152_mix_freeze_all/checkpoints/resnet152-epoch=03-val_acc=0.9403.ckpt')['state_dict'])
data = DogData(five_crop=False, batch_size=128)
predictions = trainer.predict(model, datamodule=data)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting: |          | 0/? [00:00<?, ?it/s]

In [3]:
from datetime import datetime
import pandas as pd

now = datetime.now().strftime("%Y%m%d_%H%M%S")

df = pd.read_csv(data.predict_csv)
imgs = df["id"]
columns = df.columns.tolist()
columns.pop(0)

preds = [row.tolist() for item in predictions for row in item.softmax(dim=1)]
submission = pd.concat([imgs, pd.DataFrame(preds, columns=columns)], axis=1)
submission.to_csv(f"submission_{now}.csv", index=False)